In [8]:
import numpy as np

#input_list = input("Enter 9 digits separated by spaces: ")

#string_list = input_list.split()

#number_list = [int(num) for num in string_list]


number_list = [0,1,2,3,4,5,6,7,8] #test array prior to including user input

arr3x3 = np.array([number_list[0:3],number_list[3:6],number_list[6:]])

mean_ax1 = np.array([0,0,0])
mean_ax2 = np.array([0,0,0])
var_ax1 = np.array([0,0,0])
var_ax2 = np.array([0,0,0])

for i in range(3):
    axis1 = []
    axis2 = []
    for k in range (3):
        axis1.append(arr3x3[k,i])     #collects all row k values for column i 
        axis2.append(arr3x3[i,k])    #sums all column i values for row k
    mean_ax1[i] = np.mean(axis1)
    var_ax1[i] = np.var(axis1)
    mean_ax2[i] = np.mean(axis2)
    var_ax2[i] = np.var(axis2, dtype = np.float64)         #outputs zero values, need additional decimal points

arr_flat = arr3x3.flatten()
mean_flat = np.mean(arr_flat)
var_flat = np.var(arr_flat)



print(arr3x3)
print(arr_flat)
print(mean_ax1)
print(mean_ax2)
print(mean_flat)
print(var_ax1)
print(var_ax2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[3 4 5]
[1 4 7]
4.0
[6 6 6]
[0 0 0]


Appearance of final dictionary:

```{
  'mean': [axis1, axis2, flattened],
  'variance': [axis1, axis2, flattened],
  'standard deviation': [axis1, axis2, flattened],
  'max': [axis1, axis2, flattened],
  'min': [axis1, axis2, flattened],
  'sum': [axis1, axis2, flattened]
}

Methods for manipulatng numpy arrays:

.dot: dot product (multiply elements then sum all results)