In [11]:
import numpy as np

#input_list = input("Enter 9 digits separated by spaces: ")

#string_list = input_list.split()

#number_list = [int(num) for num in string_list]


number_list = [0,1,2,3,4,5,6,7,8]

arr3x3 = np.array([number_list[0:3],number_list[3:6],number_list[6:]])

mean_ax1 = np.array([0,0,0])
mean_ax2 = np.array([0,0,0])

for i in range(3):
    sum1 = 0
    sum2 = 0
    for k in range (3):
        sum1 += arr3x3[k,i]
        sum2 += arr3x3[i,k]
    mean_ax1[i] = sum1/3
    mean_ax2[i] = sum2/3

arr_flat = arr3x3.flatten()
sum3 = 0
for i in range(len(arr_flat)):
    sum3 += arr_flat[i]

mean_flat = sum3/(len(arr_flat))

print(arr3x3)
print(arr_flat)
print(mean_ax1)
print(mean_ax2)
print(mean_flat)




[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[3 4 5]
[1 4 7]
4.0


Appearance of final dictionary:

```{
  'mean': [axis1, axis2, flattened],
  'variance': [axis1, axis2, flattened],
  'standard deviation': [axis1, axis2, flattened],
  'max': [axis1, axis2, flattened],
  'min': [axis1, axis2, flattened],
  'sum': [axis1, axis2, flattened]
}

Methods for manipulatng numpy arrays:

.dot: dot product (multiply elements then sum all results)